# Generated by Django 3.1.7 on 2021-02-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='applictaiondata',
            name='Description',
            field=models.CharField(help_text='list of value - description ', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='applictaiondata',
            name='IsCategory',
            field=models.BooleanField(help_text='list of value - category', null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='applictaiondata',
            name='Name',
            field=models.CharField(help_text='list of value - name', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='applictaiondata',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.applictaiondata', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='applictaiondata',
            name='Value',
            field=models.CharField(help_text='list of value - value', max_length=200, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='Task_Description',
            field=models.CharField(help_text='task description', max_length=200, unique=True, verbose_name='description'),
        ),
    ]
