# Generated by Django 3.1.7 on 2021-02-21 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210221_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='created',
        ),
        migrations.AddField(
            model_name='projecttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified At'),
        ),
    ]
