# Generated by Django 4.1.2 on 2022-10-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_auto_20210221_1609"),
        ("projects", "0006_auto_20200725_1307"),
    ]

    operations = []
