# Generated by Django 4.1.2 on 2022-10-07 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_merge_0003_auto_20210221_1609_0006_auto_20200725_1307"),
    ]

    operations = [
        
       
        migrations.AddField(
            model_name="projecttask",
            name="is_active",
            field=models.BooleanField(default=False, null=True),
        )
        
    ]
