# Generated by Django 4.1.2 on 2022-10-07 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_favoutite_item_alter_taskcomment_options_and_more"),
    ]

    operations = [

        migrations.AlterModelOptions(
            name="taskcomment",
            options={"ordering": ["-fav_flag", "-pk"]},
        ),
        migrations.AddField(
            model_name="projecttask",
            name="fav_flag",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="fav_flag",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="taskcomment",
            name="task_flag",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_comment",
                to="projects.projecttask",
            ),
        ),
    ]
